Repository AndelaOSP/andela-societies-backend, pull requests merged in 2018-08, with the labels that each got.

#63 [Feature #158453829] Add Notifications Package
  Makefile
  docker/release/Dockerfile
  docker/test/Dockerfile
  scripts/test.sh
  scripts/utils.sh
  src/.env.sample
  src/api/endpoints/redemption_requests.py
  src/api/utils/notifications/README.md
  src/api/utils/notifications/__init__.py
  src/api/utils/notifications/email_notices.py
  src/config.py
  src/requirements.txt
  src/tests/test_notifications.py
  src/tests/test_redemption_requests.py
  src/tests/test_user_information.py
Labels: enhancement, feature

#72 [ft #158909616] Implement Secretary review logged-activity
  Pipfile
  src/api/endpoints/logged_activities.py
  src/api/utils/auth.py
  src/api/utils/initial_data.py
  src/app.py
  src/data/cohort_data.csv
  src/manage.py
  src/tests/base_test.py
  src/tests/test_logged_activities.py
  src/tests/test_manage.py
  src/tests/test_role.py
Labels: feature

#84 Add weekly task to email success ops about pending logged activities
  src/.coveragerc
  src/api/endpoints/activity_types.py
  src/api/endpoints/logged_activities.py
  src/api/endpoints/redemption_requests.py
  src/api/endpoints/roles.py
  src/api/models.py
  src/api/utils/helpers.py
  src/api/utils/marshmallow_schemas.py
  src/api/utils/notifications/README_notifications.md
  src/api/utils/notifications/email_notices.py
  src/api/utils/notifications/task_helpers.py
  src/app.py
  src/config.py
  src/manage.py
  src/tests/base_test.py
  src/tests/test_activities.py
  src/tests/test_activity_types.py
  src/tests/test_add_cohort.py
  src/tests/test_auth.py
  src/tests/test_logged_activities.py
  src/tests/test_manage.py
  src/tests/test_model.py
  src/tests/test_notifications.py
  src/tests/test_redemption_requests.py
  src/tests/test_role.py
  src/tests/test_scheduled_tasks.py
  src/tests/test_societies.py
  src/tests/test_task_helpers.py
  src/tests/test_user_information.py
Labels: feature

#87 [Feature] Add functionalty to request info on LoggedActivity
  docker/test/Dockerfile
  src/api/endpoints/logged_activities.py
  src/api/models.py
  src/app.py
  src/tests/base_test.py
  src/tests/test_logged_activities.py
Labels: MVP, feature

#88 [ft #159521316] Send Email Notification to Finance When Redemption Request is Approved
  .gitignore
  src/api/endpoints/redemption_requests.py
  src/tests/test_redemption_requests.py
Labels: feature

#93 [Chore #160140650] refactoring redemption request.
  src/api/endpoints/cohorts/__init__.py
  src/api/endpoints/cohorts/crud.py
  src/api/endpoints/cohorts/models.py
  src/api/endpoints/logged_activities/approve.py
  src/api/endpoints/logged_activities/crud.py
  src/api/endpoints/logged_activities/models.py
  src/api/endpoints/logged_activities/reject.py
  src/api/endpoints/logged_activities/request_info.py
  src/api/endpoints/logged_activities/secretary_review.py
  src/api/endpoints/logged_activities/user_logged_activities.py
  src/api/endpoints/redemption_requests/__init__.py
  src/api/endpoints/redemption_requests/helpers.py
  src/api/endpoints/redemption_requests/marshmallow_schemas.py
  src/api/endpoints/redemption_requests/models.py
  src/api/endpoints/redemption_requests/redemption_numeration.py
  src/api/endpoints/redemption_requests/redemption_points.py
  src/api/endpoints/redemption_requests/redemption_request_funds.py
  src/api/endpoints/redemption_requests_old.py
  src/api/endpoints/societies/models.py
  src/api/models.py
  src/api/utils/helpers.py
  src/app.py
  src/config.py
  src/tests/__init__.py
  src/tests/base_test.py
Labels: chore
